config/routes.rb
Rails.application.routes.draw do
  get "pages/show"
  mount RailsAdmin::Engine => "/admin", as: "rails_admin"
  root "home#index"
  get "/landing" => "home#landing"
  get "/combo" => "home#combo"

  get "up" => "rails/health#show", as: :rails_health_check
  get "health" => "rails/health#show", as: :rails_health_check_2

  devise_for :users, {
    class_name: "User::Account",
    controllers: {
      registrations: "user/registrations",
      sessions: "user/sessions"
    },
    path: "",
    path_names: {
      sign_in: "login",
      sign_out: "logout",
      sign_up: "register",
      # password: "password"
    }
  }

  constraints CanAccessFlipperUI do
    mount Flipper::UI.app(Flipper) => "/flipper"
  end

  get "/news/" => "blog/posts#index", as: :blog_posts
  get "/news/:slug/" => "blog/posts#show", as: :blog_post

  get "/policies/:slug/" => "policy/documents#show", as: :policy_document
  get "/agreements/public-service", to: redirect("/collective-agreements/public-service-avtalet")
  get "/opinion/unions-are-good-actually" => "magazine/documents#show", as: :magazine_document

  localized do
    get "labour-market" => "labour_market/index#index", as: :labour_market

    scope module: "labour_market" do
      resources :agreements,
        only: [:index, :show],
        as: :collective_agreements
      resources :organisations,
        only: [:index, :show],
        as: :central_unions,
        defaults: { organisation_type: :central_union }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if flash[:notice].present?
      flash[:notice] = nil
      @subscription_created = true
    end
    # @subscription_created = true
  end

  def landing
    @blog_posts = Blog::Post.order(published_at: :desc)
    # flash[:notice] = "Welcome to the blog!"
    # @blog_posts = []
  end

  layout "blank", only: [:combo]
  def combo
    collective_agreement_slugs = [
      "tekniktjansteavtalet",
      "industriavtalet",
      "it-avtalet",
      "motorbranschavtalet",
    ]

    @highlighted_collective_agreements = LabourMarket::Agreement
      .where(slug: collective_agreement_slugs)
      .sort_by { |a| collective_agreement_slugs.index(a.agreement_slug) }
  end
end

app/helpers/home_helper.rb
module HomeHelper
  def render_home_index_description_markdown(markdown)
    renderer = HomeDescriptionRender.new()
    redcarpet = Redcarpet::Markdown.new(renderer, autolink: true, tables: true)
    redcarpet.render(markdown)
  end
end

class HomeDescriptionRender < Redcarpet::Render::HTML
  def paragraph(text)
    "<p class=\"mt-4 text-sm/6 text-gray-300\">#{text}</p>"
  end
end

app/views/home/combo.html.erb
<div class="flex flex-col w-full">

  <%= render :layout => "labour_market/index/section", locals: {
    heading: "kollektivavtal.nu",
    subheading: "Twenty First Century Collective Power",
  }  do %>

    <div class="mt-16" id="substack-feed-embed"></div>
    <script>
      window.SubstackFeedWidget = {
        substackUrl: "everythingisamazing.substack.com",
        posts: 4,
        layout: "center"
      };
    </script>
    <script src="https://substackapi.com/embeds/feed.js" async></script>

    <%= render partial: "labour_market/index/section-link", locals: {
      href: "https://example.org",
      text: "Newsletter &rarr;",
    } %>

  <% end %>

  <%= render :layout => "labour_market/index/section", locals: {
    heading: t("labour_market.collective_agreements"),
    subheading: "Employment terms negotiated at a sector level between employer organisations and central unions.",
  }  do %>

    <div class="mx-auto mt-16 grid auto-rows-fr grid-cols-1 gap-8 sm:mt-20 lg:mx-0 lg:max-w-none xs:grid-cols-2 lg:grid-cols-4">
      <% @highlighted_collective_agreements.each do |agreement| %>
        <% file = main_attachment(agreement) %>

        <article class="
          max-w-full
          relative 
          flex flex-col
        ">
          <div class="aspect-[707/1000] overflow-hidden rounded-2xl bg-slate-200 relative">
            <img src="<%= file.preview(resize_to_limit: [512, 512]).url %>" alt="" class="absolute inset-0 z-10 size-full object-cover">
          </div>
          <h3 class="mt-3 text-lg/6 font-semibold max-w-full text-ellipsis overflow-hidden">
            <a href="<%= collective_agreement_path(agreement) %>">
              <span class="absolute inset-0"></span>
              <%= agreement.name %>
            </a>
          </h3>
        </article>

      <% end %>
    </div>

    <%= render partial: "labour_market/index/section-link", locals: {
      href: collective_agreements_path,
      text: "More Collective Agreements &rarr;",
    } %>

  <% end %>

</div>

app/views/home/index.html.erb
<div class="deck">

  <div class="slot">

    <div class="slide bg-black text-white">

      <div class="
        absolute
        top-0
        right-0
        bottom-0
        left-0
        bg-fixed
      " style="
        background-image: url('/planet.webp');
        background-size: clamp(64px, 18vw, 256px);
        background-position: top 1rem right 0.2rem;
        background-repeat: no-repeat;
        background-origin: content-box;
      "></div>

      <div class="
        flex
        flex-col
        gap-x-2
        xxs:flex-row
      ">
        <img
          class="
            aspect-square
            h-[25px]
            w-[25px]
          "
          src="/starw.png"
        />
        <h1 class="font-bold">
          kollektivavtal.nu
        </h1>
      </div>

      <div class="
        font-major
        lowercase
        flex
        flex-row
        flex-wrap
        gap-x-3
        w-full
        slide-heading
        xxs:flex-col
        xxs:w-full
        xxs:max-w-[9ch]
        xxs:justify-self-center
        xxs:justify-center
        xxs:self-center
        xxs:flex-grow
        portrait:xxs:text-4xl
      ">
        <span class="self-start">
          <%= t("home.index.slide1.line1") %>
        </span>
        <span class="self-start
          <% if I18n.locale == :en %> xxs:pl-[1ch] <% end %>
          <% if I18n.locale == :sv %> xxs:pl-[4ch] <% end %>
        ">
          <%= t("home.index.slide1.line2") %>
        </span>
        <span class="self-start
          <% if I18n.locale == :en %> xxs:pl-[6ch] <% end %>
          <% if I18n.locale == :sv %> xxs:pl-[5ch] <% end %>
          flex-nowrap now">
          <%= t("home.index.slide1.line3") %>
        </span>
      </div>

      <ol class="
        font-light
        flex
        flex-col
        justify-end
        slide-text
      ">
        <li><%= t("home.index.slide1.power") %></li>
        <li><%= t("home.index.slide1.bargaining") %></li>
        <li><%= t("home.index.slide1.gain") %></li>
      </ol>

    </div>

  </div>

  <div class="slot relative bg-black">

    <div class="
      absolute
      top-0
      right-0
      bottom-0
      left-0
      bg-fixed
      opacity-[0.22]
    " style="
      background-image: url('/space.webp');
      background-position: center;
      background-origin: content-box;
    "></div>

    <div class="
      slide
      relative
    text-white
      xxs:landscape:grid
      xxs:landscape:items-center
      xxs:landscape:grid-cols-2
      xxs:portrait:justify-evenly
    ">


      <h2 class="
        lowercase
        font-major
        flex
        flex-row
        flex-wrap
        gap-x-3
        xxs:landscape:flex-grow
        slide-heading
      ">
        <%= t("home.index.slide2.heading") %>
      </h2>

      <p class="
        font-light
        xxs:landscape:flex-grow
        slide-text
      ">
        <%= t("home.index.slide2.text") %>
      </p>

    </div>

  </div>

  <div class="slot bg-black">
    <div class="
      slide
      text-white
      grid
      grid-cols-2
      grid-rows-2
      landscape:xl:grid-cols-3
      landscape:xl:grid-rows-1
      gap-y-8
      landscape:gap-x-8
      relative
    ">

        <ol class="flex flex-row gap-x-2 absolute bottom-0 w-full justify-center">
          <% @social_media_accounts.each do |account| %>
            <li>
              <a class="fill-slate-300 hover:fill-slate-600" href="<%= account.url %>" target="_blank" aria-label="<%= account.name %>">
                <% if account.facebook? %>
                  <%= render partial: "social_media/accounts/facebook", locals: { classes: "w-8 h-8" } %>
                <% elsif account.tiktok? %>
                  <%= render partial: "social_media/accounts/tiktok", locals: { classes: "w-8 h-8" } %>
                <% elsif account.instagram? %>
                  <%= render partial: "social_media/accounts/instagram", locals: { classes: "w-8 h-8" } %>
                <% elsif account.linkedin? %>
                  <%= render partial: "social_media/accounts/linkedin", locals: { classes: "w-8 h-8" } %>
                <% elsif account.x? %>
                  <%= render partial: "social_media/accounts/x", locals: {
                    classes: "w-8 h-8",
                    x_classes: "fill-black"
                  } %>
                <% elsif account.mastodon? %>
                  <%= render partial: "social_media/accounts/mastodon", locals: { classes: "w-8 h-8" } %>
                <% elsif account.bluesky? %>
                  <%= render partial: "social_media/accounts/bluesky", locals: {
                    classes: "w-8 h-8",
                    butteryfly_classes: "fill-black",
                  } %>
                <% end %>
              </a>
            </li>
          <% end %>
        </ol>

      <h2 class="
        font-major
        lowercase
        slide-heading
        row-start-1
        row-end-1
        col-start-1
        col-end-1
        self-end
        portrait:self-end
        landscape:xl:self-center
      ">
        <%= t("home.index.form.heading") %>
      </h2>

      <div class="slide-text landscape:max-w-lg
        landscape:col-start-1
        landscape:col-end-1
        landscape:row-start-2
        landscape:row-end-3
        portrait:col-start-2
        portrait:col-end-2
        portrait:row-start-1
        portrait:row-end-1
        portrait:self-end
        landscape:xl:self-center
        landscape:xl:col-start-3
        landscape:xl:col-end-3
        landscape:xl:row-start-1
        landscape:xl:row-end-1
      ">
        <%= t("home.index.form.text") %>
      </div>

      <div class="w-full
        flex
        flex-col
        gap-y-8
        landscape:col-start-2
        landscape:col-end-2
        landscape:row-start-1
        landscape:row-end-3
        landscape:row-span-3
        landscape:justify-center
        landscape:xl:col-start-2
        landscape:xl:col-end-2
        landscape:xl:row-start-1
        landscape:xl:row-end-1
        portrait:col-start-1
        portrait:col-end-3
        portrait:row-start-2
        portrait:row-end-2">
        <div id="custom-substack-embed"></div>
      </div>

      <script>
        window.CustomSubstackWidget = {
          substackUrl: "kollektivavtal.substack.com",
          placeholder: "example@gmail.com",
          buttonText: "Subscribe",
          theme: "custom",
          colors: {
            primary: "#FFFFFF",
            input: "#000000",
            email: "#FFFFFF",
            text: "#000000",
          },
        };
      </script>
      <script src="https://substackapi.com/widget.js" async></script>

    </div>
  </div>

  <div class="slot">
    <div class="
      slide
      bg-black
      text-white
      xxs:flex
      xxs:flex-col
      xxs:landscape:justify-evenly
    ">

      <h2 class="
        font-major
        lowercase
        xxs:landscape:text-center
        slide-heading
      ">
        <%= t("home.index.capacity.heading") %>
      </h2>

      <ol class="
        flex
        flex-col
        xxs:portrait:flex-grow
        xxs:justify-evenly
        xxs:landscape:grid
        xxs:landscape:grid-cols-3
        xxs:landscape:w-full
      ">
        <% list = [
          { img: "c1.webp", text: t("home.index.capacity.resources") },
          { img: "c2.webp", text: t("home.index.capacity.organise") },
          { img: "c3.webp", text: t("home.index.capacity.network") }
        ] %>
        <% list.each do |item| %>
          <li class="
            flex
            flex-col
            xxs:gap-y-4
            xxs:portrait:text-center
            xxs:landscape:text-center
          ">
            <img src="<%= item[:img] %>" class="
              h-16
              object-contain
              self-start
              xxs:self-center
              lg:h-32
            " />
            <span class="slide-text"><%= item[:text] %></span>
          </li>
        <% end %>
      </ol>

    </div>
  </div>

  <div class="slot">
    <div class="
      slide
      bg-black
      text-white
      xxs:flex
      xxs:landscape:flex-row
      xxs:landscape:items-center
      xxs:portrait:flex-col
      xxs:portrait:justify-between
    ">


      <h2 class="
        lowercase
        font-major
        slide-heading
        xxs:landscape:flex-1
      ">
        Focus
      </h2>

      <ol class="
        flex
        flex-col
        flex-grow
        xxs:landscape:flex-1
        xxs:landscape:h-full
        xxs:landscape:justify-evenly
        xxs:portrait:justify-evenly
      ">
        <% list = [
          { text: t("home.index.focus.text1"), word: t("home.index.focus.subheading1") },
          { text: t("home.index.focus.text2"), word: t("home.index.focus.subheading2") },
          { text: t("home.index.focus.text3"), word: t("home.index.focus.subheading3") }
        ] %>
        <% list.each do |item| %>
          <li class="
            flex
            flex-col
            xxs:gap-y-4
          ">
            <h3 class="
              lowercase
              slide-subheading
              font-major
            "><%= item[:word] %></h3>
            <span class="
              slide-text
            "><%= item[:text] %></span>
          </li>
        <% end %>
      </ol>

    </div>
  </div>

  <div class="slot bg-white">
    <div class="
      slide
      bg-white
      text-black
      xxs:flex
      xxs:flex-col
      xxs:justify-evenly
    ">

      <h2 class="
        lowercase
        font-major
        xxs:flex
        xxs:flex-col
        md:text-3xl
        lg:text-6xl
        font-extrabold
        whitespace-nowrap
      ">
        <span class="pl-[1ch]">
          <%= t("home.index.footer.heading1") %>
        </span>
        <span class="">
          <%= t("home.index.footer.heading2") %>
        </span>
      </h2>

      <ul class="
        slide-text
      ">
        <li>
          <%= t("home.index.footer.no1") %>
        </li>
        <li>
          <%= t("home.index.footer.no2") %>
        </li>
        <li>
          <%= t("home.index.footer.no3") %>
        </li>
      </ul>

      <p class="
        lowercase
        font-bold
        font-major
        xxs:flex
        xxs:flex-col
        slide-subheading
        md:text-2xl
        lg:text-5xl
        whitespace-nowrap
      ">
        <span class="">
          <%= t("home.index.footer.power") %>
        </span>
        <span class="">
          <%= t("home.index.footer.gain") %>
        </span>
      </p>

      <div class="
        flex
        flex-col
        xxs:flex-row
        xxs:items-center
        xxs:gap-x-2
      ">
        <img src="/starb.png" class="aspect-square w-[20px]" />
        <span class="text-xl font-bold">
          kollektivavtal.nu
        </span>
      </div>

    </div>
  </div>

</div>