config/routes.rb
Rails.application.routes.draw do
  get "pages/show"
  mount RailsAdmin::Engine => "/admin", as: "rails_admin"
  root "home#index"
  get "/landing" => "home#landing"
  get "/combo" => "home#combo"

  get "up" => "rails/health#show", as: :rails_health_check
  get "health" => "rails/health#show", as: :rails_health_check_2

  devise_for :users, {
    class_name: "User::Account",
    controllers: {
      registrations: "user/registrations",
      sessions: "user/sessions"
    },
    path: "",
    path_names: {
      sign_in: "login",
      sign_out: "logout",
      sign_up: "register",
      # password: "password"
    }
  }

  constraints CanAccessFlipperUI do
    mount Flipper::UI.app(Flipper) => "/flipper"
  end

  get "/news/" => "blog/posts#index", as: :blog_posts
  get "/news/:slug/" => "blog/posts#show", as: :blog_post

  get "/policies/:slug/" => "policy/documents#show", as: :policy_document
  get "/agreements/public-service", to: redirect("/collective-agreements/public-service-avtalet")
  get "/opinion/unions-are-good-actually" => "magazine/documents#show", as: :magazine_document

  localized do
    get "labour-market" => "labour_market/index#index", as: :labour_market

    scope module: "labour_market" do
      resources :agreements,
        only: [:index, :show],
        as: :collective_agreements
      resources :organisations,
        only: [:index, :show],
        as: :central_unions,
        defaults: { organisation_type: :central_union }
    end
  end
end

app/models/labour_market.rb
module LabourMarket
  def self.table_name_prefix
    "labour_market_"
  end
end

app/models/labour_market/agreement.rb
class LabourMarket::Agreement < ApplicationRecord
  scope :lexicographical, -> { order(agreement_name: :asc) }
  scope :chronological, -> { order(created_at: :asc) }
  scope :reverse_chronological, -> { order(created_at: :desc) }
  has_many :documents, class_name: "LabourMarket::Document", dependent: :destroy, inverse_of: :agreement
  has_many :signatures, class_name: "LabourMarket::Signature", dependent: :destroy, inverse_of: :agreement
  has_many :members, through: :signatures, source: :organisation
  has_many :references, as: :referenceable
  has_many :translations, as: :translatable

  enum :agreement_visibility, [
    :agreement_hidden,
    :agreement_public,
  ]

  scope :description_missing, -> { where(agreement_description: [nil, ""]) }
  scope :description_present, -> { where.not(agreement_description: [nil, ""]) }

  scope :scope_missing, -> { where(agreement_scope: [nil, ""]) }
  scope :scope_present, -> { where.not(agreement_scope: [nil, ""]) }

  scope :documents_missing, -> {
    left_outer_joins(:documents)
      .where(labour_market_documents: { id: nil })
      .distinct
  }

  scope :documents_present, -> {
    left_outer_joins(:documents)
      .where.not(labour_market_documents: { id: nil })
      .distinct
  }

  scope :organisations_missing, -> {
    left_outer_joins(:signatures)
      .where(labour_market_signatures: { id: nil })
      .distinct
  }

  scope :organisations_present, -> {
    left_outer_joins(:signatures)
      .where.not(labour_market_signatures: { id: nil })
      .distinct
  }

  scope :references_missing, -> {
    left_outer_joins(:references)
      .where(labour_market_references: { id: nil })
  }

  scope :references_present, -> {
    left_outer_joins(:references)
      .where.not(labour_market_references: { id: nil })
      .distinct
  }

  scope :translations_missing, -> {
    left_outer_joins(:translations)
      .where(labour_market_translations: { id: nil })
  }

  scope :translations_present, -> {
    left_outer_joins(:translations)
      .where.not(labour_market_translations: { id: nil })
      .distinct
  }

  scope :agreement_complete, -> {
    description_present
      .scope_present
      .documents_present
      .organisations_present
      .references_present
      .translations_present
  }

  scope :agreement_incomplete, -> {
    base_query = left_outer_joins(:documents, :signatures, :references, :translations)
    base_query.where(agreement_description: [nil, ""])
      .or(base_query.where(agreement_scope: [nil, ""]))
      .or(base_query.where(labour_market_documents: { id: nil }))
      .or(base_query.where(labour_market_signatures: { id: nil }))
      .or(base_query.where(labour_market_references: { id: nil }))
      .or(base_query.where(labour_market_translations: { id: nil }))
      .distinct
  }

  before_create :set_slug
  def set_slug
    if self.agreement_slug.blank?
      self.agreement_slug = self.agreement_name.parameterize
    end
  end

  before_update :update_slug
  def update_slug
    if self.agreement_name_changed?
      self.agreement_slug = self.agreement_name.parameterize
    end
  end

  def agreement_complete?
    props = [
      :agreement_name,
      :agreement_description,
      :agreement_scope,
    ]
    return false if props.any? do |attribute|
      self.send(attribute).blank?
    end
    return false if self.documents.empty?
    return false if self.members.empty?
    return false if self.translations.empty?
    return true
  end

  rails_admin do
    object_label_method do
      :agreement_name
    end

    list do
      scopes [
        nil,
        :agreement_complete,
        :agreement_incomplete,
        :agreement_hidden,
        :agreement_public,
      ]
      field :agreement_complete?, :boolean do
        label "Ready?"
      end

      field :agreement_name
      field :agreement_slug
      field :created_at
      field :updated_at
      sort_by :created_at
    end

    create do
      field :agreement_name
      field :agreement_slug
      field :agreement_description
      field :agreement_scope
      field :agreement_visibility
      field :references
    end

    edit do
      field :agreement_name
      field :agreement_slug
      field :agreement_description
      field :agreement_scope
      field :agreement_visibility
      field :members
      field :references
      field :translations
    end

    show do
      field :agreement_name
      field :agreement_slug

      field :agreement_complete?, :boolean

      field :missing_fields do
        label "Missing Fields"
        pretty_value do
          bindings[:view].content_tag(:ul) {
            value.map do |field|
              bindings[:view].content_tag(:li, field)
            end.join.html_safe
          }.html_safe
        end

        visible do
          bindings[:object].agreement_complete? == false
        end
      end

      field :agreement_description
      field :agreement_scope
      field :agreement_visibility
      field :members
      field :documents

      configure :documents do
        pretty_value do
          bindings[:view].content_tag(:ul) {
            value.map do |field|
              bindings[:view].content_tag(:li) {
                "[#{
                  bindings[:view].content_tag(:a,
                    style: "font-family: monospace",
                    href: "/admin/labour_market~document/#{field.id}"
                  ) { field.id[0..7] }}]
                #{
                  bindings[:view].content_tag(:span) { field.document_name }
                }".html_safe
              }.html_safe
            end.join.html_safe
          }.html_safe
        end
      end

      field :references do
        pretty_value do
          bindings[:view].content_tag(:ul) {
            value.map do |field|
              bindings[:view].content_tag(:li) {
                "[#{
                  bindings[:view].content_tag(:a,
                    style: "font-family: monospace",
                    href: "/admin/labour_market~reference/#{field.id}"
                  ) { field.id[0..4] }}]
                #{
                  bindings[:view].content_tag(:a,
                    # style: "font-family: monospace",
                    href: field.url
                  ) { field.url }
                }".html_safe
              }.html_safe
            end.join.html_safe
          }.html_safe
        end
      end

      field :translations

      field :translations do
        pretty_value do
          bindings[:view].content_tag(:ul) {
            value.map do |field|
              bindings[:view].content_tag(:li) {
                "[#{
                  bindings[:view].content_tag(:a,
                    style: "font-family: monospace",
                    href: "/admin/labour_market~translation/#{field.id}"
                  ) { field.translation_type }}]
                #{
                  bindings[:view].content_tag(:span) { field.translation_text }
                }".html_safe
              }.html_safe
            end.join.html_safe
          }.html_safe
        end
      end
    end
  end

  def missing_fields
    fields = []
    fields << "Name" if self.agreement_name.blank?
    fields << "Description" if self.agreement_description.blank?
    fields << "Scope" if self.agreement_scope.blank?
    fields << "Documents" if self.documents.empty?
    fields << "Organisations" if self.members.empty?
    fields << "Translations" if self.translations.empty?
    fields << "References" if self.references.empty?
    fields
  end

  def to_param
    agreement_slug
  end
end

app/models/labour_market/agreement_document.rb
class LabourMarket::AgreementDocument < ApplicationRecord
  belongs_to :version, class_name: "LabourMarket::AgreementVersion", foreign_key: "version_id"
  has_one_attached :file

  include Translatable
  translates :name

  rails_admin do
    list do
      field :file
      field :name
      field :created_at
      field :updated_at
      sort_by :created_at
    end
  end
end

app/models/labour_market/agreement_membership.rb
class LabourMarket::AgreementMembership < ApplicationRecord
  belongs_to :agreement, class_name: "LabourMarket::Agreement"
  belongs_to :organisation, class_name: "LabourMarket::Organisation"

  rails_admin do
    list do
      field :agreement
      field :organisation
      field :created_at
      field :updated_at
      sort_by :created_at
    end
  end
end

app/models/labour_market/collective_agreement.rb
class LabourMarket::CollectiveAgreement < ApplicationRecord
  validates :name, presence: true
  validates :slug, presence: true, uniqueness: true
  scope :chronological, -> { order(created_at: :asc) }
  scope :reverse_chronological, -> { order(created_at: :desc) }
  has_many :versions, class_name: "LabourMarket::CollectiveAgreementVersion", dependent: :destroy, inverse_of: :agreement
  has_one_attached :image
  has_many :signatures, class_name: "LabourMarket::CollectiveAgreementSignature", dependent: :destroy, inverse_of: :agreement
  has_many :signatories, through: :signatures, source: :organisation

  rails_admin do
    configure :name do
      sticky true
      column_width 256
    end
  end

  def to_param
    slug
  end

  def latest_version
    versions.reverse_chronological.first
  end
end

app/controllers/labour_market/agreements_controller.rb
class LabourMarket::AgreementsController < ApplicationController
  around_action :set_locale_from_url

  def index
    if I18n.locale == :sv
      @agreements = LabourMarket::Agreement
        .agreement_public
        .lexicographical
        .joins(:documents)
        .includes(:documents)
    else
      @agreements = LabourMarket::Agreement
        .agreement_public
        .joins(:documents)
        .includes(:documents)
        .joins(:translations)
        .includes(:translations)
        .where(labour_market_translations: { translation_language: I18n.locale.to_s })
      @agreements = @agreements.sort_by do |agreement|
        translation = agreement.translations.find { |t| t.agreement_name? }
        if translation.present?
          translation.translation_text || agreement.agreement_name
        else
          agreement.agreement_name
        end
      end
    end
    render action: "index", layout: "page"
  end

  def show
    @agreement = LabourMarket::Agreement
      .left_outer_joins(:documents, :translations)
      .includes(:documents, :translations)
      .find_by_agreement_slug(params[:id])
    if @agreement.blank?
      raise ActiveRecord::RecordNotFound
    end
    render action: "show", layout: "one-two-three"
  end
end

app/controllers/labour_market/index_controller.rb
class LabourMarket::IndexController < ApplicationController
  layout "page"
  around_action :set_locale_from_url

  def index
    collective_agreement_slugs = [
      "tekniktjansteavtalet",
      "motorbranschavtalet",
      "industriavtalet",
    ]

    @highlighted_collective_agreements = LabourMarket::Agreement
      .where(agreement_slug: collective_agreement_slugs)
      .sort_by { |a| collective_agreement_slugs.index(a.agreement_slug) }

    central_union_slugs = [
      "if-metall",
      "unionen",
      "kommunal",
    ]

    @highlighted_central_unions = LabourMarket::Organisation
      .where(organisation_slug: central_union_slugs)
  end
end

app/controllers/labour_market/organisations_controller.rb
class LabourMarket::OrganisationsController < ApplicationController
  around_action :set_locale_from_url

  def index
    @organisation_type = params[:organisation_type]
    @organisations = LabourMarket::Organisation
      .where(organisation_type: params[:organisation_type])
      .order(:organisation_name)
    @letters = @organisations.map { |o| o.organisation_name.upcase }.uniq.sort
    render action: "index", layout: "page"
  end

  def show
    puts params.inspect
    @organisation_type = params[:organisation_type]
    @organisation = LabourMarket::Organisation.find_by_organisation_slug(params[:id])
    @agreements = @organisation.agreements.agreement_public
    render action: "show", layout: "one-two-three"
  end
end

app/controllers/labour_market_controller.rb
class LabourMarketController < ApplicationController
  layout "page"
  around_action :set_locale_from_url

  def index
    collective_agreement_slugs = [
      "tekniktjansteavtalet",
      "motorbranschavtalet",
      "industriavtalet",
    ]

    @highlighted_collective_agreements = LabourMarket::Agreement
      .where(slug: collective_agreement_slugs)
      .sort_by { |a| collective_agreement_slugs.index(a.slug) }

    central_union_slugs = [
      "if-metall",
      "unionen",
      "kommunal",
    ]

    @highlighted_central_unions = LabourMarket::Organisation
      .where(slug: central_union_slugs)
      .sort_by { |a| central_union_slugs.index(a.slug) }
  end
end

app/helpers/labour_market/agreements_helper.rb
module LabourMarket::AgreementsHelper
  def agreement_name(agreement)
    if I18n.locale == :sv
      return agreement.agreement_name
    end
    translation = agreement.translations.find {
      |t| t.agreement_name? and t.translation_language == I18n.locale.to_s
    }
    if translation.present?
      return translation.translation_text
    end
    return agreement.agreement_name
  end

  def agreement_scope(agreement)
    if I18n.locale == :sv
      return agreement.agreement_scope
    end
    translation = agreement.translations.find {
      |t| t.agreement_scope? and t.translation_language == I18n.locale.to_s
    }
    if translation.present?
      return translation.translation_text
    end
    return agreement.agreement_scope
  end

  def agreement_description(agreement)
    if I18n.locale == :sv
      return agreement.agreement_description
    end
    translation = agreement.translations.find {
      |t| t.agreement_description? and t.translation_language == I18n.locale.to_s
    }
    if translation.present?
      return translation.translation_text
    end
    return agreement.agreement_description
  end

  def main_attachment(agreement)
    return nil if agreement.documents.empty?
    main_document = agreement.documents.where(main_document: true).find { |d| d.file.attached? }
    return nil if main_document.nil?
    return main_document.file
  end

  def render_agreement_description(agreement)
    renderer = AgreementDescriptionRenderer.new()
    redcarpet = Redcarpet::Markdown.new(renderer, tables: true)
    markdown = agreement_description(agreement)
    return redcarpet.render(agreement_description(agreement)) if markdown.present?
    return ""
  end
end

class AgreementDescriptionRenderer < Redcarpet::Render::HTML
  def header(text, header_level)
    "<h#{header_level} class=\"text-lg mdtext-2xl font-bold\">#{text}</h#{header_level}>"
  end

  def link(href, title, text)
    %(<a class="text-blue-700 underline" href="#{href}">#{text}</a>)
  end

  def paragraph(text)
    "#{text}"
  end
end

app/helpers/labour_market/collective_agreements_helper.rb
module LabourMarket::CollectiveAgreementsHelper
  def render_collective_agreement_description(agreement)
    renderer = CollectiveAgreementDescriptionRenderer.new()
    redcarpet = Redcarpet::Markdown.new(renderer, tables: true)
    redcarpet.render(agreement.description_en)
  end
end

class CollectiveAgreementDescriptionRenderer < Redcarpet::Render::HTML
  def header(text, header_level)
    "<h#{header_level} class=\"text-lg mdtext-2xl font-bold\">#{text}</h#{header_level}>"
  end

  def link(href, title, text)
    %(<a class="text-blue-700 underline" href="#{href}">#{text}</a>)
  end
end


class BlogPostRender < Redcarpet::Render::HTML

  def header(text, header_level)
    case header_level
    when 1
      %(
          <h1 class="text-lg mdtext-2xl font-bold">
            #{text}
          </h#{header_level}>

        )
    else
      %(
          <h#{header_level} class="text-lg mdtext-2xl font-bold">
            #{text}
          </h#{header_level}>"
        )
    end
  end

  def link(href, title, text)
    %(<a class="text-blue-700 underline" href="#{href}">#{text}</a>)
  end
end

app/views/labour_market/organisations/_list.html.erb
<table class="min-w-full divide-y divide-gray-300">
  <thead>
    <tr>
      <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-0 sr-only">Name</th>
    </tr>
  </thead>
  <tbody class="divide-y divide-gray-200 bg-white">

    <% organisations.each do |organisation| %>
      <tr class="">
        <td class="group relative whitespace-nowrap py-5 pl-4 pr-3 text-sm sm:pl-0">
          <div class="flex items-center">
            <div class="size-11 rounded-lg bg-slate-100 overflow-hidden border-slate-200 border-2">
              <img
                class="size-11"
                <% logo = organisation_logo(organisation) %>
                <% if logo.present? %>
                  src="<%= logo.url %>"
                <% else %>
                  src="https://placehold.co/64x64"
                <% end %>
                alt=""
              />
            </div>
            <div class="ml-4">
              <div class="font-medium text-gray-900">
                <a href="<%= organisation_path(organisation) %>" class="underline text-sky-600">
                  <span class="absolute -inset-x-0 -inset-y-0 -z-20"></span>
                  <%= organisation.organisation_name %>
                </a>
              </div>
            </div>
          </div>
        </td>
      </tr>
    <% end %>

  </tbody>
</table>

app/views/labour_market/organisations/index.html.erb
<div class="flex flex-col">

  <%= render partial: "ui/breadcrumbs", locals: {
    links: [
      { href: labour_market_path, text: t("labour_market.root") },
    ]
  } %>

  <%= render partial: "ui/heading-plus-subheading", locals: {
    heading: case @organisation_type
      when :central_union
        t("labour_market.central_unions")
      when :employer_association
        t("labour_market.employer_associations")
      when :local_union
        t("labour_market.local_unions")
    end,
    subheading: t("labour_market.central_unions_subheading")
  } %>

  <div class="mt-8 flow-root">
    <div class="-mx-4 -my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
      <div class="inline-block min-w-full py-2 align-middle sm:px-6 lg:px-8">
        <%= render partial: "labour_market/organisations/list", locals: {
          organisations: @organisations
        } %>
      </div>
    </div>
  </div>
</div>

app/views/labour_market/organisations/show.html.erb
<% content_for :one do %>
  <% if @organisation.central_union? %>
    <%= render partial: "ui/breadcrumbs", locals: {
      links: [
        { href: labour_market_path, text: t("labour_market.root") },
        { href: central_unions_path, text: t("labour_market.central_unions") },
      ]
    } %>
  <% elsif @organisation.employer_association? %>
    <%= render partial: "ui/breadcrumbs", locals: {
      links: [
        { href: labour_market_path, text: t("labour_market.root") },
        { href: employer_associations_path, text: t("labour_market.employer_associations") },
      ]
    } %>
  <% elsif @organisation.local_union? %>
    <%= render partial: "ui/breadcrumbs", locals: {
      links: [
        { href: labour_market_path, text: t("labour_market.root") },
        { href: local_unions_path, text: t("labour_market.local_unions") },
      ]
    } %>
  <% end %>

  <%= render partial: "ui/heading-plus-subheading", locals: {
    heading: @organisation.organisation_name,
    subheading: render_organisation_description(@organisation).html_safe,
  } %>

<% end %>

<% content_for :two do %>
  <% logo = organisation_logo(@organisation) %>
  <%= render partial: "ui/profile-pic", locals: {
    div: "",
    img: "object-cover",
    src: logo.present? ? logo.url : "https://placehold.co/512x512",
    alt: "",
  } %>

  <dl class="divide-y divide-gray-100 max-w-full overflow-hidden">

    <% if @organisation.local_union? and !@organisation.parents.empty? %>
      <div class="lg:px-4 py-4">
        <dt class="text-sm font-medium leading-6 text-gray-900">
          <%= t("labour_market.central_union") %>
        </dt>
        <dd class="mt-1 text-sm leading-6 text-gray-700 max-w-full overflow-hidden">
          <a href="<%= central_union_path(@organisation.parents.first) %>" class="text-sky-600 underline"><%= @organisation.parents.first.name %></a>
        </dd>
      </div>
    <% end %>

    <% if @organisation.website.present? %>
      <div class="lg:px-4 py-4">
        <dt class="text-sm font-medium leading-6 text-gray-900">
          <%= t("website") %>
        </dt>
        <dd class="mt-1 text-sm leading-6 text-gray-700 max-w-full overflow-hidden">
          <a href="<%= @organisation.website %>" class="text-sky-600 underline"><%= @organisation.website %></a>
        </dd>
      </div>
    <% end %> 

    <% if current_user and current_user.role?("labour_market_admin") %>
      <div class="lg:px-4 py-4">
        <dt class="text-sm font-medium leading-6 text-gray-900">
          Labour Market Admin
        </dt>
        <dd class="mt-1 text-sm leading-6 text-gray-700 max-w-full overflow-hidden">
          <%= link_to "Edit #{@organisation.organisation_name}", rails_admin.edit_path(model_name: 'labour_market~organisation', id: @organisation.id), class: "text-sky-600 underline" %>
        </dd>
      </div>
    <% end %>

  </dl>
<% end %>

<% content_for :three do %>
  <div class="flex flex-col space-y-8">
    <% if @organisation.local_union? and @agreements.count > 0 %>
      <section class="flex flex-col gap-y-4">
        <h2 class="text-xl font-semibold text-gray-900">
          Collective Agreement
        </h2>

        <%= render partial: "labour_market/agreements/list", locals: {
          agreements: @agreements.first(1)
        } %>

      </section>
    <% end %>

    <% if @organisation.central_union? or @organisation.employer_association? and @agreements.count > 0 %>
      <section class="flex flex-col gap-y-4">
        <h2 class="text-xl font-semibold text-gray-900">
          <%= t("labour_market.collective_agreements") %>
        </h2>

        <%= render partial: "labour_market/agreements/list2", locals: {
          agreements: @agreements
        } %>
      </section>
    </div>
  <% end %> 
<% end %>